NN module dataset and dataloader gredient training of nn on some data transformer code

PyTorch makes differentiation (computing gradients) easy and efficient by providing the autograd package. This allows you to automatically compute the gradients of tensors during backpropagation, which is essential for training machine learning models, particularly in deep learning.

cpu - numpy
gpu - pytorch

#Concept of autograd
#NN Module of Pytorch
#Dataset and Dataloader

In [28]:
def dy_dx(x):
  return 2*x

In [39]:
dy_dx(4)

8

In [40]:
import torch
x=torch.tensor(3.0,requires_grad=True)

In [41]:
x

tensor(3., requires_grad=True)

In [42]:
y=x**2 ##FORWARD PROPAGATION

In [43]:
y ##############forward propagation

tensor(9., grad_fn=<PowBackward0>)

In [44]:
y=2*x

In [45]:
y

tensor(6., grad_fn=<MulBackward0>)

In [46]:
##to cal derivate we have to do back
y.backward()

In [47]:
x.grad

tensor(2.)

In [48]:
import math
def dz_dx(x):
    return 2*x*math.cos(x**2)

In [49]:
dz_dx(3)

-5.466781571308061

In [50]:
dz_dx(5)

9.912028118634735

In [51]:
x=torch.tensor(3.0,requires_grad=True)

In [52]:
x

tensor(3., requires_grad=True)

In [53]:
y=x**2
z=torch.sin(y)

In [54]:
y

tensor(9., grad_fn=<PowBackward0>)

In [ ]:
z

tensor(0.4121, grad_fn=<SinBackward0>)

In [55]:
z.backward() ########calculate gradient

In [56]:
x.grad

tensor(-5.4668)

In [58]:
import torch.nn as nn

In [98]:
###CONSTRUCTOR OF PARENT CLASS(nn.Module)
class Model(nn.Module):
    def __init__(self,new_features):
        super().__init__()
        self.linear=nn.Linear(new_features,1) ###  features and 1 is hidden layer
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out


In [99]:
torch.rand(10,5)

tensor([[0.9191, 0.0656, 0.6829, 0.7186, 0.5106],
        [0.2955, 0.0997, 0.6014, 0.4595, 0.5742],
        [0.3450, 0.0459, 0.5531, 0.0040, 0.1201],
        [0.9197, 0.5622, 0.4236, 0.4814, 0.2392],
        [0.0670, 0.6430, 0.6900, 0.0669, 0.0693],
        [0.4561, 0.6038, 0.1852, 0.6167, 0.6331],
        [0.6297, 0.9893, 0.9392, 0.1004, 0.8215],
        [0.1081, 0.5007, 0.2819, 0.3029, 0.1524],
        [0.3776, 0.7217, 0.1744, 0.7189, 0.9823],
        [0.7392, 0.3778, 0.3517, 0.8522, 0.3114]])

In [100]:
data=torch.rand(10,5)

In [101]:
data.shape

torch.Size([10, 5])

In [102]:
data.shape[1] ### 5 is the features

5

In [103]:
model = Model(data.shape[1])###initialize

In [104]:
class test:
  def __init__(self):
      print("hello from init")
  def __call__(self):
      print("hello from call")
  def testing(self):
      print("hello from testing")

In [105]:
obj=test()

hello from init


In [106]:
obj.testing()

hello from testing


In [107]:
obj() ### object as a function is called then we get "hello from call" -> if we call object as a function in backend we call def __call__(self). so inside nn.module we have function(def__call(self))

hello from call


In [108]:
model(data)

tensor([[0.5068],
        [0.5181],
        [0.5198],
        [0.5369],
        [0.5208],
        [0.5117],
        [0.5496],
        [0.5600],
        [0.4873],
        [0.5018]], grad_fn=<SigmoidBackward0>)

In [109]:
model.forward(data)

tensor([[0.5068],
        [0.5181],
        [0.5198],
        [0.5369],
        [0.5208],
        [0.5117],
        [0.5496],
        [0.5600],
        [0.4873],
        [0.5018]], grad_fn=<SigmoidBackward0>)